apiVersion: v1
description: The easy, open source way for everyone in your company to ask questions
  and learn from data.
name: metabase
version: 0.14.1
appVersion: v0.39.3
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg
sources:
- https://github.com/metabase/metabase
